spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/web_applications
    username: postgres
    password: password
    hikari:
      maximumPoolSize: 2
      connectionTimeout: 40000
  jpa:
    hibernate:
      ddl-auto: create

security:
  auth:
    expiration-time: 900000
    secret: 0QMGQG5hOTOz70Wcux3plkdPI1bsEEgTwu653ktgBSpgqBug8virdblKcCji
    refresh-token-expiration-time: 86400000
  ant-patterns: /api/v1/auth/**
