spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moja_baza?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: uzytkownik
    password: MojeHaslo
    hikari:
      maximum-pool-size: 2
      connection-timeout: 40000
    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect

security:
  auth:
    expiration-time: 900000
    secret: 0QMGQG5hOTOz70Wcux3plkdPI1bsEEgTwu653ktgBSpgqBug8virdblKcCji
    refresh-token-expiration-time: 86400000
  ant-patterns: /api/v1/auth/**
